version: '3.8'

services:
  family-tree:
    build: .
    container_name: family_tree_app
    ports:
      - "8080:8080"
    volumes:
      # проброс бд и медиа папки, чтобы данные не пропали при перезапуске
      - ./data:/app/data
      - ./media:/app/media
    restart: unless-stopped
